### ISSUE TITLE
Project Name and Project Path

### ISSUE THREAD

**Issue by juanpedromoreno** [47deg/sbt-org-policies#158]
At this moment, we're using the sbt setting `name` with two main purposes: create url paths/urls pointing to the project and project naming (used in different files like README, CONTRIBUTING, LICENSE, etc.). 

However, we should create as many new settings as we need to be able to personalize the project configuration. For example, for the second case, `orgProjectName` for example, by default with the `name` sbt setting value.

**Comment by fedefernandez** [comment]
For example: https://travis-ci.org/47deg/sbt-org-policies/builds/222830858#L3022
