### ISSUE TITLE
Update dependency org.scala-lang:scala-library:provided

### ISSUE THREAD

**Issue by 47degdev** [47deg/sbt-org-policies#43]
Actual version: 2.10.6
 Patch: -
 Minor: 2.12.1
 Major: -

**Comment by juanpedromoreno** [comment]
We should allow excluding some dependencies to be updated, since plugins need to be developed with scala 2.10.

`dependencyUpdatesExclusions := moduleFilter(organization = "org.scala-lang")`

Does it possible through sbt-dependencies @fedefernandez ?

**Comment by fedefernandez** [comment]
Yes, it's possible and it should be activated by default for `org.scala-lang`. 

See [here](https://github.com/47deg/sbt-dependencies/blob/2782466b15e386515559f781e01a5a593c9924e3/src/main/scala/dependencies/DependenciesPlugin.scala#L85)

**Comment by juanpedromoreno** [comment]
Seems it's not working though, the plugin created this issue :P

**Comment by fedefernandez** [comment]
Yeah, I know, I'll take a look to see why it's not applying the default settings

**Comment by juanpedromoreno** [comment]
Sounds good, thanks!
