### ISSUE TITLE
Fix Release Command/Task

### ISSUE THREAD

**Issue by juanpedromoreno** [47deg/sbt-org-policies#637]
After the plugin has been upgraded to cross-built with 1.0.1, `orgPublishRelease` is not working when `orgAfterCISuccess` is invoked.

**Comment by suhasgaddam** [comment]
I think this is an example of a silent failure: https://travis-ci.org/frees-io/sbt-freestyle/builds/277277811

`orgPublishRelease` just didn't run even though it was supposed to according to the logs. At least, there was no logs showing that `orgPublishRelease` ran.
