### ISSUE TITLE
Travis cross scala versions matching project cross scala versions

### ISSUE THREAD

**Issue by suhasgaddam** [47deg/sbt-org-policies#649]
`orgScriptCI` should have caught this issue https://github.com/47deg/github4s/pull/166.

But it looks like `orgScriptTaskListSetting` "suffers" from the same issue as `orgAfterCISuccess`. The task/command won't run unless it is the latest Scala version in the `crossScalaVersions` sequence.

https://travis-ci.org/47deg/github4s/jobs/279420156#L957

**Comment by juanpedromoreno** [comment]
Probably is disabled by default, but I think the following piece of biz should check the cross scala versions:

https://github.com/47deg/sbt-org-policies/blob/b79af0895a3691106e2fae7a358206f8396c9f4a/core/src/main/scala/sbtorgpolicies/rules/ValidationFunctions.scala#L73-L103

**Comment by suhasgaddam** [comment]
Yup, disabled by default. Simple fixes could be
* switch from `asRunnableItem` to `asRunnableItemFull`
* create a `RunnableItemConfigScope` with `crossScalaVersions = true` for `orgValidateFiles`

The `orgValidateFiles` task with `asRunnableItem` syntax
https://github.com/47deg/sbt-org-policies/blob/v0.7.5/src/main/scala/sbtorgpolicies/settings/DefaultSettings.scala#L139

which sets `crossScalaVersions` to `false`
https://github.com/47deg/sbt-org-policies/blob/v0.7.5/core/src/main/scala/sbtorgpolicies/runnable/syntax.scala#L42-L43

The `orgScriptCI` command
https://github.com/47deg/sbt-org-policies/blob/v0.7.5/src/main/scala/sbtorgpolicies/settings/bash.scala#L75-L77

The filtering
https://github.com/47deg/sbt-org-policies/blob/v0.7.5/src/main/scala/sbtorgpolicies/settings/bash.scala#L115-L119

**Comment by fedefernandez** [comment]
I'm thinking about comparing the `major.minor` version without the `patch` part.

```scala
val scalaBinaryV  = extracted.get(scalaBinaryVersion)
val isLastScalaV  = crossV.lastOption.exists(v => majorMinor(v) == scalaBinaryV)
```

**Comment by fedefernandez** [comment]
WIP with this approach #709
