### ISSUE TITLE
Updated pbdirect to 0.0.4

### ISSUE THREAD

**Issue by eperinan** [47deg/sbt-org-policies#691]
I discovered a bug related with divergin implicit resolution and consequence of this, they just fixed the bug and there is a new version.

https://github.com/btlines/pbdirect/commit/1a60b960448d76b83264198d1fbbbd91d3edf340

Could you update this number version please?

I could change the version and send a PR but I don't know what is the procedure to check that all works fine after change one specific version.

**Comment by juanpedromoreno** [comment]
Feel free to open a PR bumping up the version. You could also remove the Snapshot suffix in the version.sbt file, in our to release a new patch version.
