### ISSUE TITLE
Requirements enforcement across all org projects

### ISSUE THREAD

**Issue by raulraja** [47deg/sbt-org-policies#8]
As an effort to clean up all of our projects we want to achieve the following goals which may be enforced with this plugin.

- Enforce AutoHeader plugin with the org copyright note
- Add License file defaulting to ASL2
- Add Maintainers/Contributors file which keeps itself up to date perhaps using Github4s
- Monitor dependencies and provide issues/PR for auto updating dependencies
- Enforce library versions so they are all aligned withing the org projects
- Enforce README "used by" section in all repositories
@juanpedromoreno Feel free to add more things here as discussed

**Comment by raulraja** [comment]
Let's also add https://github.com/47deg/sbt-dependencies so all downtream dependent projects get the benefit of warning as libraries get outdated.

**Comment by juanpedromoreno** [comment]
All of these enforcement requirements, and other additional ones, have been added through different smaller issues. This can be considered as duplicate.
